### ISSUE TITLE
Not deploying on OVH

### ISSUE THREAD

**Issue by pirix-gh** [kubicorn/kubicorn#647]
Using OVH
Ubuntu 16.04
Machine B2-7

```
2018-07-01T16:36:56Z [ℹ]  Selected [fs] state store
2018-07-01T16:36:56Z [ℹ]  Loaded cluster: myfirstk8s
2018-07-01T16:36:56Z [ℹ]  Init Cluster
2018-07-01T16:36:57Z [ℹ]  Query existing resources
2018-07-01T16:36:57Z [ℹ]  Resolving expected resources
2018-07-01T16:36:57Z [ℹ]  Reconciling
2018-07-01T16:36:57Z [✔]  Created Network [82d8832a-5d55-4e6f-a0db-4884519e14ee]
2018-07-01T16:36:58Z [✔]  Created Subnet [b4ee524e-67b2-4423-90d6-b8c12b4dd7b9]
2018-07-01T16:36:58Z [✔]  Created SecurityGroup [6a5023cd-6d20-4873-ab8c-2a0339ac6095]
2018-07-01T16:36:59Z [ℹ]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kubicorn/bootstrap/master/ovh_k8s_ubuntu_16.04_master.sh]
2018-07-01T16:36:59Z [✖]  Error during apply of atomic reconciler, attempting clawback: Expected HTTP response code [201 202] when accessing [POST https://compute.gra5.cloud.ovh.net/v2/0f38475ae21e457eac4374278e3b139a/servers], but got 400 instead
{"badRequest": {"message": "Invalid input for field/attribute name. Value: . u'' is too short", "code": 400}}
2018-07-01T16:36:59Z [!]  
2018-07-01T16:36:59Z [!]  Attempting to backtrack and cleanup created resources.
2018-07-01T16:36:59Z [!]  
2018-07-01T16:36:59Z [✔]  Deleted SecurityGroup [6a5023cd-6d20-4873-ab8c-2a0339ac6095]
2018-07-01T16:37:01Z [✔]  Deleted Subnet [b4ee524e-67b2-4423-90d6-b8c12b4dd7b9]
2018-07-01T16:37:02Z [✔]  Deleted Network [82d8832a-5d55-4e6f-a0db-4884519e14ee]
2018-07-01T16:37:02Z [✖]  Unable to commit state store: Nil cluster spec

```

Seems to communicate well to GRA5 but fails with the API

**Comment by xmudrii** [comment]
I think this is related to #639, which should fix the issue, but is still not merged.

Also, #642 is a docs update which states some additional requirements for OVH (that PR is already merged).

If you're willing to test it, you can checkout from #642 and try to get it running. If it works for you, I'll happily merge the PR. I currently don't have access to OVH, so I can't give it a try, but I believe it should resolve issues.

Thanks!

**Comment by xmudrii** [comment]
@pirix-gh I've merged #639 as well. I think that should fix OVH/OpenStack issues.

Before creating the cluster, you need to update Kubicorn, which you can do using `go get -u github.com/kubicorn/kubicorn`.

If you have any problems, let me know and I'll try my best to resolve the issues. Thanks!

**Comment by pirix-gh** [comment]
Tested & it's got a SegFault
```

2018-07-01T17:54:06Z [ℹ]  Selected [fs] state store
2018-07-01T17:54:06Z [ℹ]  Loaded cluster: myfirstk8s
2018-07-01T17:54:06Z [ℹ]  Init Cluster
2018-07-01T17:54:06Z [ℹ]  Query existing resources
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x140 pc=0x14807ee]

goroutine 1 [running]:
github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources.(*Subnet).immutableRender(0xc4208fa280, 0x2a15260, 0xc4208fa370, 0xc420374000, 0x0)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/subnet.go:198 +0x78e
github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources.(*Subnet).Actual(0xc4208fa280, 0xc420374000, 0x2, 0xc4208d9da8, 0xc4208def40, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/subnet.go:73 +0x142
github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Actual(0xc4208deba0, 0xc420374000, 0xc420374000, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:50 +0x10a
github.com/kubicorn/kubicorn/cmd.runApply(0xc4203e4180, 0x5974f0, 0xc4205e1ca8)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:134 +0x625
github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc4203ae6c0, 0xc4202342e0, 0x1, 0x1)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:60 +0x6d
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203ae6c0, 0xc420234290, 0x1, 0x1, 0xc4203ae6c0, 0xc420234290)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a74360, 0xc4205e1f60, 0x1687a2e, 0x1be6f98)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x30e
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x2a74360, 0x0, 0xc420321500)
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
github.com/kubicorn/kubicorn/cmd.Execute()
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/cmd/root.go:76 +0x31
main.main()
	/home/ubuntu/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20
```

**Comment by pirix-gh** [comment]
@xmudrii Yes, I deleted everything and started from the beginning
http://kubicorn.io/documentation/ovh-walkthrough.html

**Comment by xmudrii** [comment]
Okay, thanks for the response. It's late over here right now, but I'll try to fix it tomorrow if I can. I'll post the update here once I have some more information about the problem and fix.

**Comment by xmudrii** [comment]
The problem described in this issue seems to be resolved, however another one appeared.

To make it easier to track the progress on fixing issues, I'm going to close this issue in favor of #655, as it is the most recent one and contains details about the most recent problem found.

Thanks a lot for reporting the issues!
